### ISSUE TITLE
Emacs Crashes With "Stack smashing detected"

### ISSUE THREAD

**Issue by cuichaox** [portacle/portacle#60] opened 2017-12-13 08:19 UTC
```
$pwd
/home/cuichao/portacle/portacle
$gnome-open portacle.desktop 
$ ./portacle.run 
Warning: arch-dependent data dir '/home/linus/portacle/lin/emacs/libexec/emacs/25.2/x86_64-unknown-linux-gnu/': No such file or directory
Warning: Lisp directory '/home/linus/portacle/lin/emacs/share/emacs/25.2/lisp': No such file or directory
Fatal error 11: Segmentation fault
Backtrace:
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4f7962]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4df509]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4f67de]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4f69e3]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4f6a1a]
/home/cuichao/portacle/portacle//lin/lib/libpthread.so.0(+0x10330)[0x7f431e33f330]
/home/cuichao/portacle/portacle//lin/lib/libc.so.6(+0x27e3d)[0x7f431da6ee3d]
/usr/lib/x86_64-linux-gnu/gconv/ISO8859-1.so(gconv+0x26d)[0x7f43116f2a0d]
/home/cuichao/portacle/portacle//lin/lib/libc.so.6(+0x2359a)[0x7f431da6a59a]
/home/cuichao/portacle/portacle//lin/lib/libc.so.6(iconv+0x57)[0x7f431da69b47]
/home/cuichao/portacle/portacle//lin/lib/libglib-2.0.so.0(g_convert_with_iconv+0x135)[0x7f431fe08925]
/home/cuichao/portacle/portacle//lin/lib/libglib-2.0.so.0(g_convert+0x68)[0x7f431fe08b68]
/home/cuichao/portacle/portacle//lin/lib/libglib-2.0.so.0(g_locale_to_utf8+0x4a)[0x7f431fe091fa]
/home/cuichao/portacle/portacle//lin/lib/libglib-2.0.so.0(+0x52376)[0x7f431fe2e376]
/home/cuichao/portacle/portacle//lin/lib/libglib-2.0.so.0(+0x5299f)[0x7f431fe2e99f]
/home/cuichao/portacle/portacle//lin/lib/libglib-2.0.so.0(g_option_context_parse+0x762)[0x7f431fe301d2]
/home/cuichao/portacle/portacle//lin/lib/libgtk-x11-2.0.so.0(gtk_parse_args+0x8e)[0x7f432118626e]
/home/cuichao/portacle/portacle//lin/lib/libgtk-x11-2.0.so.0(gtk_init_check+0x9)[0x7f43211862c9]
/home/cuichao/portacle/portacle//lin/lib/libgtk-x11-2.0.so.0(gtk_init+0x9)[0x7f43211862f9]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4c36c4]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4c5a17]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x550b26]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x584055]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x550953]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x551e4c]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x550a4a]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x584055]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x550953]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x584055]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x550953]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x584055]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x54fb13]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x54fe5e]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x553321]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x54f3fd]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4e1ffc]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x54f3ab]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4df9e6]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4e3e84]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x4e41a5]
/home/cuichao/portacle/portacle//lin/emacs/bin/emacs[0x412cc8]
...
*** stack smashing detected ***: /home/cuichao/portacle/portacle//lin/launcher/portacle terminated

$uname -a
Linux dagger 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

cat /etc/debian_version 
9.3
```

**Comment by Shinmera** [comment] 2017-12-13 08:21
I've seen this "stack smashing" before, but I can't remember where, or what the solution was.

**Comment by tanju-b** [comment] 2017-12-28 02:58
I am also not able to run portacle.desktop on Ubuntu 16.04.3 (Xfce desktop)

Double clicking on the Portacle icon on window just causes a minor flash but nothing ever starts up

From command line:
`tj@sparky:~/portacle$ exo-open portacle.desktop
tj@sparky:~/portacle$ dirname: missing operand
Try 'dirname --help' for more information.
bash: ./portacle.run: No such file or directory

./portacle.run
./portacle.run: line 7: /home/tj/portacle//lin/launcher/portacle: cannot execute binary file: Exec format error
`

**Comment by Shinmera** [comment] 2017-12-28 08:27
What is "exo-open"? Did you mean xdg-open?

**Comment by tanju-b** [comment] 2017-12-28 16:26
yea sorry I am a noob.  exo-open seems to be specific to Xfce UI, after searching around a bit, I'm not sure I'm using it correctly.

I running i686 Intel  (this is a pretty old laptop I found buried in closet that I am trying to resurrect for learning)

`tj@sparky:~$ lscpu
Architecture:          i686
CPU op-mode(s):        32-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 13
Model name:            Intel(R) Celeron(R) M processor         1.30GHz
Stepping:              8
CPU MHz:               1297.134
BogoMIPS:              2594.26
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov clflush dts acpi mmx fxsr sse sse2 ss tm pbe nx bts`

**Comment by Shinmera** [comment] 2017-12-29 07:55
As the website states, Portacle is currently only available for x64 devices.

**Comment by Shinmera** [comment] 2017-12-29 09:10
What you could try to do however is build Portacle yourself. I haven't tested this, so I can't guarantee it will work, but have a look at the [build instructions](https://github.com/portacle/portacle/blob/master/build/README.md#linux) if you're feeling adventurous.

**Comment by tanju-b** [comment] 2017-12-30 03:29
Oops sorry for not reading the requirements on the website.  I'm going to pass on the build.   on side a note I was successful installing/running portacle on a different Windows 7 (x64) machine a few days prior.
Thanks!

**Comment by Shinmera** [comment] 2018-05-11 17:47
@cuichaox Can you test again with [the latest release](https://github.com/portacle/portacle/releases/tag/1.1c)? I can't reproduce your issue.

**Comment by Shinmera** [comment] 2018-08-22 21:41
Closing for now. Please re-open if this is still an issue.

**Closed by Shinmera** 2018-08-22 21:41 UTC
Labels: can't reproduce, portability
