### ISSUE TITLE
it doesn't work on- Mac OS 11.4(bigSur)...

### ISSUE THREAD

**Issue by M-a-k-l-o-v** [portacle/portacle#159] opened 2021-11-16 15:21 UTC
<img width="998" alt="142012384-484de0cb-6eae-46ce-abd0-5d2181e143d0" src="https://user-images.githubusercontent.com/89027053/142013289-5fd87f67-b6b2-4577-b09a-7af2e2d5b640.png">
it doesn't work for mine

**Comment by metayan** [comment] 2021-11-16 16:00
The relevant error message is at the very bottom of the screendump. Not sure, but this error **might** be caused by Portacle not having access to the Desktop folder.

If you have enough trust, and the option is still available on your version of macOS, you can try this:

#### In `Preferences`-`Security&Privacy`-`Privacy` tab, choose `Full Disk Access` on the left and select `Portacle.app` on the right.


I do this when macOS starts complaining about Portacle's access to different folders, which is whenever I rebuild or reinstall Portacle, so quite seldom.

Works for Catalina, but one can hope that there is some similar way even on newer versions of macOS.

Can you let us know if it works - and if it's different from Catalina, maybe post a dump of what the `Preferences` window looks like? If it doesn't work, I'll edit this comment appropriately.

(Funny, by the way, that your user name is obscured at the top, but left clear at the bottom of the dump.)

Also, it's often fine to paste just the text from the report. Easier to copy from... ;)

**Comment by M-a-k-l-o-v** [comment] 2021-11-16 17:59
<img width="1416" alt="Screenshot 2021-11-16 at 9 58 44 PM" src="https://user-images.githubusercontent.com/89027053/142039953-ab5e4099-9997-4bfb-b9fd-fbca9022663f.png">
it has full disk access and this is the end of the error screen

**Comment by M-a-k-l-o-v** [comment] 2021-11-16 18:04
I think this might be an issue with the bigSur update- but if there is a way around this, pls let me know.

**Comment by Shinmera** [comment] 2022-07-27 13:42
Hi. Please try the latest pre-release: https://github.com/portacle/portacle/releases/tag/1.4c
It was created under macOS 12, so it may not launch on older versions. I'd be interested to know about that.
It's been signed using a self-signed certificate, which must first be installed using the mac-fixup.sh script. The script will also clear security attributes. Unfortunately there's no way to make the script runnable via a simple double-click, so it has to be done via the terminal.

Closing this, as all mac problems are pretty much the same atm. Please continue discussions in #127

**Closed by Shinmera** 2022-07-27 13:42 UTC
